name: Deploy
 
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        default: 'next'
        description: What version tag do you want to deploy?
        required: true
        options: 
          - next
          - rc
          - latest
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: install dependencies
        run: yarn install

      - name: build admin ui
        run: yarn build:admin
