name: Deploy
 
on:
  push
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: install dependencies
        run: yarn install

      - name: build admin ui
        run: yarn build:admin
        
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "victor@medusajs.com"
